// Author: Mason Powell
// Date: 08/05/2018
// Purpose: SmartCard issued to registered students, stores the Student name, date of birth, ID, issue date, and SmartCardNumber

package main;

import java.util.*;

public class SmartCard {
	private Name stuName;
	private Date dateOfBirth;
	private ID stuID;
	private Date issueDate;
	private SCNumber stuNumber;
	
	public SmartCard(Student stu){
		setStuName(stu.getPersonalName());
		setDateOfBirth(stu.getDob());
		setIssueDate();
		setStuID(stu.getPersonalID());
		setStuNumber(stu);
	}
	
	public Name getStuName() {
		/**
		 * Returns the students name, taken from the Student object
		 * 
		 * Returns:
		 * A Name object containing the students first and last name as well as their initials
		 * Example Usage:
		 * getStuName();
		 */
		
		return stuName;
	}

	private void setStuName(Name stuName) {
		/**
		 * Sets the student name for this card
		 * 
		 * Parameters:
		 * stuName -- a Name object containing a students first and last name as well as their initials, taken from the Student object
		 * Example Usage:
		 * setStuName()
		 */
		
		this.stuName = stuName;
	}

	public Date getDateOfBirth() {
		/**
		 * Returns the students date of birth, taken from the Student object
		 * 
		 * Returns:
		 * A Date object containing the students date of birth
		 * Example Usage:
		 * getDateOfBirth();
		 */
		
		return dateOfBirth;
	}

	private void setDateOfBirth(Date dateOfBirth) {
		/**
		 * Sets the students date of birth for this card
		 * 
		 * Parameters:
		 * dateOfBirth -- a Date object containing the students date of birth, taken from the Student object
		 * Example Usage:
		 * setDateOfBirth()
		 */
		
		this.dateOfBirth = dateOfBirth;
	}

	public ID getStuID() {
		/**
		 * Returns the students ID, taken from the Student object
		 * 
		 * Returns:
		 * An ID object containing a letter and a number
		 * Example Usage:
		 * getStuID();
		 */
		
		return stuID;
	}

	private void setStuID(ID stuID) {
		/**
		 * Sets the students ID for this card
		 * 
		 * Parameters:
		 * stuID -- an ID object containing a letter and a number, taken from the Student object
		 * Example Usage:
		 * setStuID()
		 */
		
		this.stuID = stuID;
	}

	public Date getIssueDate() {
		/**
		 * Returns the smartcard's issue date
		 * 
		 * Returns:
		 * A Date object containing the date the SmartCard object was created
		 * Example Usage:
		 * getIssueDate();
		 */
		
		return issueDate;
	}

	private void setIssueDate() {
		/**
		 * Sets the issue date for this card, a new Date set to the current date
		 *
		 * Example Usage:
		 * setIssueDate()
		 */
		
		this.issueDate = new Date();
	}

	public SCNumber getStuNumber() {
		/**
		 * Returns the students smartcard number, generated by setStuNumber()
		 * 
		 * Returns:
		 * An SCNumber object containg the students initials, the cards issue date, and a randomly generated number
		 * Example Usage:
		 * getStuNumber();
		 */
		
		return stuNumber;
	}

	private void setStuNumber(Student stu) {
		/**
		 * Sets the students smartcard number for this card
		 * 
		 * Parameters:
		 * stu -- a Student object used to access the initials
		 * Example Usage:
		 * setStuNumber()
		 */
		
		this.stuNumber = SmartCardNumberFactory.getInstance(stu.getPersonalName().getInitials(), getIssueDate());
	}
	
	
}
